/** Fail closed: a static frontend with no reachable private API is not a beta. */
import { writeFile } from 'node:fs/promises';
const origin = process.env.STUDIO_API_ORIGIN;
const license = process.env.VITE_TLDRAW_LICENSE_KEY;
const missing = ['STUDIO_API_ORIGIN', 'STUDIO_PROXY_SIGNING_SECRET', 'VITE_TLDRAW_LICENSE_KEY'].filter(k => !process.env[k]);
if (missing.length) throw new Error('Beta deployment is not configured. Missing: ' + missing.join(', ') + '. Keep service secrets in Netlify runtime settings.');
const url = new URL(origin);
if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash || ['localhost', '127.0.0.1', '::1'].includes(url.hostname)) throw new Error('STUDIO_API_ORIGIN must be a reachable HTTPS service origin without credentials, path or query.');
const result = await fetch(new URL('/api/deployment-readiness', url), { signal: AbortSignal.timeout(10000), redirect: 'error' });
if (!result.ok) throw new Error('Private beta API readiness check failed: HTTP ' + result.status);
const readiness = await result.json();
const requirements = ['invite_only', 'secure_sessions', 'proxy_signature_verified', 'metadata_only_tracing'];
if (readiness.mode !== 'private-beta' || requirements.some(k => readiness[k] !== true)) throw new Error('Backend has not declared all private-beta deployment gates. This local pilot must not be exposed directly.');
await writeFile('netlify.beta.toml', `# Generated by deploy/prepare-netlify.mjs. No secret values included.\n[build]\n  command = "npm run build"\n  publish = "dist"\n\n[[redirects]]\n  from = "/api/*"\n  to = "${url.origin}/api/:splat"\n  status = 200\n  force = true\n  signed = "STUDIO_PROXY_SIGNING_SECRET"\n\n[[redirects]]\n  from = "/*"\n  to = "/index.html"\n  status = 200\n\n[[headers]]\n  for = "/api/*"\n  [headers.values]\n    Cache-Control = "private, no-store"\n\n[[headers]]\n  for = "/*"\n  [headers.values]\n    X-Content-Type-Options = "nosniff"\n    Referrer-Policy = "strict-origin-when-cross-origin"\n    X-Frame-Options = "DENY"\n    Permissions-Policy = "camera=(), microphone=(), geolocation=()"\n`);
console.log('Wrote Netlify beta config. Validate API-origin response caching, cookies, signature rejection and the canvas license on the actual preview before inviting participants.');
