import {chromium} from 'playwright';
import fs from 'node:fs';import assert from 'node:assert/strict';
const root='../beta-runtime/data/',fixture=JSON.parse(fs.readFileSync(root+'browser-fixture.json'));
const b=await chromium.launch({executablePath:'/home/chaiwithjai/Documents/code/ale/experiments/gb10/.browsers/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const errors=[],checks=[];const url='https://imagine-together-dharmic-beta.netlify.app';
async function page(){const c=await b.newContext({viewport:{width:1450,height:1000}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);return p;}
async function req(p,path,method='GET',body){return p.evaluate(async({path,method,body})=>{const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-Workspace-ID':localStorage.getItem('imagine-together.workspace')||''},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok)throw Error(r.status+': '+await r.text());return r.json();},{path,method,body});}
async function register(p,suffix,code){await p.getByRole('button',{name:'Have an invitation? Create an account'}).click();await p.getByLabel('Name',{exact:true}).fill(fixture.name+suffix);await p.getByLabel('Password',{exact:true}).fill(fixture.password);await p.getByLabel('Beta invitation',{exact:true}).fill(code);await p.getByRole('button',{name:'Create account',exact:true}).click();await p.getByLabel('New workspace name').waitFor();}
try{
 const owner=await page();await register(owner,' owner',fixture.code);checks.push('Invited registration through hosted UI and secure session');
 await owner.getByLabel('New workspace name').fill('Grant workflow verification');await owner.getByRole('button',{name:'Create workspace',exact:true}).click();await owner.getByRole('heading',{name:'Our swipe file'}).waitFor();const wid=await owner.evaluate(()=>localStorage.getItem('imagine-together.workspace'));
 await owner.getByRole('button',{name:'Capture something'}).click();await owner.getByLabel('Title',{exact:true}).fill('Fictional grant source — verification only');await owner.getByLabel('Source URL or reference',{exact:true}).fill('https://maven.com/a-plus');await owner.getByLabel('Original passage',{exact:true}).fill('Synthetic passage: community members should define the problem together.');await owner.getByLabel('Team note',{exact:true}).fill('Unfinished fixture thought: how do we include people who cannot attend live?');await owner.getByRole('button',{name:'Save to swipe file'}).click();await owner.reload();await owner.getByRole('heading',{name:'Our swipe file'}).waitFor();let cards=(await req(owner,'/cards')).cards;assert.equal(cards.length,1);checks.push('Source and unfinished thought survive hosted page reload');
 await owner.getByRole('button',{name:'People & workspaces'}).click();await owner.getByLabel('Invite role').selectOption('editor');await owner.getByRole('button',{name:'Create invitation',exact:true}).click();const token=await owner.locator('textarea[readonly]').first().inputValue();await owner.getByRole('button',{name:'Done',exact:true}).click();
 const guest=await page();await register(guest,' guest',token);await guest.getByRole('button',{name:/Grant workflow verification/}).click();await guest.getByRole('heading',{name:'Our swipe file'}).waitFor();assert.equal((await req(guest,'/cards')).cards[0].id,cards[0].id);checks.push('One invited collaborator joins the correct private workspace');
 const people=(await req(owner,'/workspaces/'+wid+'/members')).members;let doc=await req(owner,'/canonical');doc=await req(owner,'/canonical','PUT',{revision:doc.revision,title:'Verification grant brief',body:'Fictional plan: invite community input before drafting. Open question: participation beyond live sessions.',source_card_ids:[cards[0].id],required_reviewers:people.map(x=>x.user_id)});
 const review={revision:doc.revision,content_hash:doc.content_hash,decision:'approve',reason:'Automated fixture workflow approval; not real grant or model feedback'};
 await req(owner,'/canonical/review','POST',review);let disputed=await req(guest,'/canonical/review','POST',{...review,decision:'changes_requested'});assert.equal(disputed.aligned,false);let agreed=await req(guest,'/canonical/review','POST',review);assert.equal(agreed.aligned,true);await req(owner,'/canonical/publish','POST',{revision:doc.revision,content_hash:doc.content_hash});checks.push('Separate reviewer disagreement and exact-revision publication');
 await owner.getByRole('button',{name:'Alignment & decisions'}).click();await owner.getByLabel('Working title').waitFor();assert.equal(await owner.getByLabel('Working title').inputValue(),'Verification grant brief');await owner.screenshot({path:root+'hosted-alignment.png'});
 await owner.getByRole('button',{name:'Sources & workspace'}).click();await owner.locator('.source-card input[type=checkbox]').first().check();await owner.getByRole('button',{name:/Ask Bonsai/}).click();await owner.getByLabel('What would help you think?').fill('Ask one useful question about this fictional grant plan. One sentence.');await owner.getByRole('button',{name:'Make a suggestion',exact:true}).click();await owner.locator('.suggestion-text').waitFor({timeout:180000});const suggestion=await owner.locator('.suggestion-text').innerText();assert.ok(suggestion.trim());const jobs=(await req(owner,'/jobs')).jobs;const job=jobs.find(x=>x.state==='succeeded');assert.ok(job);const evidence=await req(owner,'/jobs/'+job.id+'/evidence');assert.equal((await req(owner,'/cards')).cards[0].quote,cards[0].quote);checks.push('Real hosted UI → Netlify → GB10 → Bonsai suggestion; source unchanged');
 await owner.screenshot({path:root+'hosted-suggestion.png'});assert.deepEqual(errors,[]);
 fs.writeFileSync(root+'hosted-verification.json',JSON.stringify({status:'PASS',checks,errors,workspace:wid,job_id:job.id,trace_id:job.trace_id,run_id:job.run_id,source_unchanged:true,human_model_feedback:'NOT_SUBMITTED'},null,2));console.log(JSON.stringify({status:'PASS',checks,trace_id:job.trace_id,run_id:job.run_id,errors}));
}catch(e){console.error(String(e));fs.writeFileSync(root+'hosted-verification.json',JSON.stringify({status:'FAIL',checks,errors,error:String(e)}));process.exitCode=1;}finally{await b.close();}
